# Generated by Django 6.0 on 2025-12-29 14:23

from django.db import migrations, models
from django.utils.text import slugify


def populate_slugs(apps, schema_editor):
    BlogPost = apps.get_model('blogs', 'BlogPost')
    for post in BlogPost.objects.all():
        base = slugify(post.title) or f'post-{post.pk}'
        candidate = base
        idx = 1
        while BlogPost.objects.filter(slug=candidate).exclude(pk=post.pk).exists():
            idx += 1
            candidate = f"{base}-{idx}"
        post.slug = candidate
        post.save(update_fields=['slug'])


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
                ('slug', models.SlugField(blank=True, max_length=60, unique=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.AddField(
            model_name='blogpost',
            name='cover_url',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='blogpost',
            name='slug',
            field=models.SlugField(blank=True, max_length=220),
        ),
        migrations.AddField(
            model_name='blogpost',
            name='summary',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='blogpost',
            name='tags',
            field=models.ManyToManyField(blank=True, related_name='posts', to='blogs.tag'),
        ),
        migrations.RunPython(populate_slugs, reverse_code=migrations.RunPython.noop),
        migrations.AlterField(
            model_name='blogpost',
            name='slug',
            field=models.SlugField(blank=True, max_length=220, unique=True),
        ),
    ]
